import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1774865693313 implements MigrationInterface {
    name = 'AutoMigration1774865693313'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Guard for environments where base schema already exists (for example
        // DB created earlier via synchronize/manual bootstrap). In that case,
        // running this generated "baseline" migration would fail on enum/table
        // already-exists errors and block app startup.
        const hasUsersTable = await queryRunner.hasTable("users");
        if (hasUsersTable) {
            return;
        }

        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'accountant', 'staff', 'snooker_staff')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "passwordHash" character varying(255) NOT NULL, "fullName" character varying(120) NOT NULL, "email" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'staff', "isActive" boolean NOT NULL DEFAULT true, "assignedReports" text array NOT NULL DEFAULT '{}', "assignedModules" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "punchInAt" TIMESTAMP WITH TIME ZONE NOT NULL, "punchOutAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(80) NOT NULL, "description" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c46e6d713bc0107af340db99c8a" UNIQUE ("name"), CONSTRAINT "PK_c8efa29d4848b2abaea47237a87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ingredients_unit_enum" AS ENUM('mcg', 'mg', 'g', 'kg', 'quintal', 'ton', 'ml', 'cl', 'dl', 'l', 'gallon', 'pcs', 'piece', 'count', 'unit', 'units', 'pair', 'dozen', 'tray', 'plate', 'pack', 'packet', 'box', 'bottle', 'can', 'jar', 'tub', 'pouch', 'roll', 'bag', 'sack', 'bundle', 'carton', 'crate', 'loaf', 'block', 'cup', 'tablespoon', 'teaspoon', 'custom')`);
        await queryRunner.query(`CREATE TABLE "ingredients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "categoryId" uuid NOT NULL, "unit" "public"."ingredients_unit_enum" NOT NULL, "perUnitPrice" numeric(12,2) NOT NULL DEFAULT '0', "minStock" numeric(12,3) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a955029b22ff66ae9fef2e161f8" UNIQUE ("name"), CONSTRAINT "PK_9240185c8a5507251c9f15e0649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ingredientId" uuid NOT NULL, "totalStock" numeric(14,3) NOT NULL DEFAULT '0', "lastUpdatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ab41ce837971278c768894802b" UNIQUE ("ingredientId"), CONSTRAINT "REL_7ab41ce837971278c768894802" UNIQUE ("ingredientId"), CONSTRAINT "PK_db4062dc343b2b80535e72e2b9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ingredient_stock_logs_type_enum" AS ENUM('ADD', 'ALLOCATE', 'USE', 'ADJUST')`);
        await queryRunner.query(`CREATE TABLE "ingredient_stock_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ingredientId" uuid NOT NULL, "type" "public"."ingredient_stock_logs_type_enum" NOT NULL, "quantity" numeric(14,3) NOT NULL, "note" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7a56967cd89daa66071afd1069a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ingredientId" uuid NOT NULL, "date" date NOT NULL, "allocatedQuantity" numeric(14,3) NOT NULL DEFAULT '0', "usedQuantity" numeric(14,3) NOT NULL DEFAULT '0', "remainingQuantity" numeric(14,3) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4a93bdbf6dea1a70909ebc9d608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_daily_allocation_ingredient_date_unique" ON "daily_allocations" ("ingredientId", "date") `);
        await queryRunner.query(`CREATE TABLE "pos_billing_controls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isBillingEnabled" boolean NOT NULL DEFAULT true, "enforceDailyAllocation" boolean NOT NULL DEFAULT true, "reason" character varying(255), "updatedByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_014121c6e2fc85028e570e9763a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_closing_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "staffId" uuid NOT NULL, "reportDate" date NOT NULL, "closingSlot" integer NOT NULL DEFAULT '1', "isCarryForwardClosing" boolean NOT NULL DEFAULT false, "totalIngredients" integer NOT NULL DEFAULT '0', "totalExpectedRemaining" numeric(14,3) NOT NULL DEFAULT '0', "totalReportedRemaining" numeric(14,3) NOT NULL DEFAULT '0', "totalVariance" numeric(14,3) NOT NULL DEFAULT '0', "items" jsonb NOT NULL DEFAULT '[]'::jsonb, "note" character varying(600), "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_263ae79f07a6b700023ed5ceaa9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_staff_closing_reports_staff_reportDate_unique" ON "staff_closing_reports" ("staffId", "reportDate") `);
        await queryRunner.query(`CREATE TABLE "item_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "description" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_88b385fb344dc44577a3f9e6a76" UNIQUE ("name"), CONSTRAINT "PK_db3359595abacbe15cf2f89c07e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "categoryId" uuid NOT NULL, "sellingPrice" numeric(12,2) NOT NULL DEFAULT '0', "gstPercentage" numeric(6,2) NOT NULL DEFAULT '0', "imageUrl" character varying(1024), "note" character varying(500), "estimatedIngredientCost" numeric(14,3) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_213736582899b3599acaade2cd1" UNIQUE ("name"), CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."item_ingredients_unit_enum" AS ENUM('mcg', 'mg', 'g', 'kg', 'quintal', 'ton', 'ml', 'cl', 'dl', 'l', 'gallon', 'pcs', 'piece', 'count', 'unit', 'units', 'pair', 'dozen', 'tray', 'plate', 'pack', 'packet', 'box', 'bottle', 'can', 'jar', 'tub', 'pouch', 'roll', 'bag', 'sack', 'bundle', 'carton', 'crate', 'loaf', 'block', 'cup', 'tablespoon', 'teaspoon', 'custom')`);
        await queryRunner.query(`CREATE TABLE "item_ingredients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemId" uuid NOT NULL, "ingredientId" uuid NOT NULL, "quantity" numeric(14,3) NOT NULL, "unit" "public"."item_ingredients_unit_enum" NOT NULL, "normalizedQuantity" numeric(14,6) NOT NULL DEFAULT '0', "costContribution" numeric(14,3) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0e1d40e3d15d1ee05f63691a350" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_item_ingredient_unique" ON "item_ingredients" ("itemId", "ingredientId") `);
        await queryRunner.query(`CREATE TABLE "add_ons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "sellingPrice" numeric(12,2) NOT NULL DEFAULT '0', "gstPercentage" numeric(6,2) NOT NULL DEFAULT '0', "imageUrl" character varying(1024), "note" character varying(500), "estimatedIngredientCost" numeric(14,3) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_262fd74d3c83cd52222179e0b88" UNIQUE ("name"), CONSTRAINT "PK_16b0b20fb9aec455ea78e6065cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."add_on_ingredients_unit_enum" AS ENUM('mcg', 'mg', 'g', 'kg', 'quintal', 'ton', 'ml', 'cl', 'dl', 'l', 'gallon', 'pcs', 'piece', 'count', 'unit', 'units', 'pair', 'dozen', 'tray', 'plate', 'pack', 'packet', 'box', 'bottle', 'can', 'jar', 'tub', 'pouch', 'roll', 'bag', 'sack', 'bundle', 'carton', 'crate', 'loaf', 'block', 'cup', 'tablespoon', 'teaspoon', 'custom')`);
        await queryRunner.query(`CREATE TABLE "add_on_ingredients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "addOnId" uuid NOT NULL, "ingredientId" uuid NOT NULL, "quantity" numeric(14,3) NOT NULL, "unit" "public"."add_on_ingredients_unit_enum" NOT NULL, "normalizedQuantity" numeric(14,6) NOT NULL DEFAULT '0', "costContribution" numeric(14,3) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9977a537946e963682a795d4b56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_add_on_ingredient_unique" ON "add_on_ingredients" ("addOnId", "ingredientId") `);
        await queryRunner.query(`CREATE TABLE "combos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "sellingPrice" numeric(12,2) NOT NULL DEFAULT '0', "gstPercentage" numeric(6,2) NOT NULL DEFAULT '0', "imageUrl" character varying(1024), "note" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e160bce8577758c165a8d9397f1" UNIQUE ("name"), CONSTRAINT "PK_5b4bab633aee439e2bade42cc3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "combo_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comboId" uuid NOT NULL, "itemId" uuid NOT NULL, "quantity" numeric(10,3) NOT NULL DEFAULT '1', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f633e0564e3422d489c5cebe2e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_combo_item_unique" ON "combo_items" ("comboId", "itemId") `);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discounttype_enum" AS ENUM('percentage', 'fixed_amount', 'free_item')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "couponCode" character varying(60) NOT NULL, "title" character varying(140), "description" character varying(600), "discountType" "public"."coupons_discounttype_enum" NOT NULL, "discountValue" numeric(12,2), "minimumOrderAmount" numeric(12,2), "maximumDiscountAmount" numeric(12,2), "maxUses" integer, "usagePerUserLimit" integer, "firstTimeUserOnly" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "validFrom" TIMESTAMP WITH TIME ZONE NOT NULL, "validUntil" TIMESTAMP WITH TIME ZONE NOT NULL, "freeItemCategoryId" uuid, "freeItemId" uuid, "totalUsageCount" integer NOT NULL DEFAULT '0', "internalNote" character varying(500), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d46eefa53cfb29b6227b32c053d" UNIQUE ("couponCode"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupon_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "couponId" uuid NOT NULL, "userId" uuid, "orderId" character varying(80), "usedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "discountAmountApplied" numeric(12,2), "freeItemId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_01ff9a1cac559c4ae2e4179d0a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "refreshTokenHash" character varying(128) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP WITH TIME ZONE, "userAgent" character varying(512), "ipAddress" character varying(64), "clientType" character varying(20) NOT NULL DEFAULT 'web', "lastUsedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_641507381f32580e8479efc36cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_expires_at" ON "auth_sessions" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_user_id" ON "auth_sessions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(160), "notes" character varying(600), "sourceDeviceId" character varying(80), "createdByUserId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_customers_phone_unique" ON "customers" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_ordertype_enum" AS ENUM('takeaway', 'dine_in', 'delivery', 'snooker')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_kitchenstatus_enum" AS ENUM('not_sent', 'queued', 'preparing', 'ready', 'served')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('pending', 'paid', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_paymentmode_enum" AS ENUM('cash', 'card', 'upi', 'mixed')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying(40) NOT NULL, "idempotencyKey" character varying(120), "orderReference" character varying(80), "customerId" uuid, "staffId" uuid NOT NULL, "branchId" character varying(64), "deviceId" character varying(80), "orderType" "public"."invoices_ordertype_enum" NOT NULL DEFAULT 'takeaway', "tableLabel" character varying(40), "kitchenStatus" "public"."invoices_kitchenstatus_enum" NOT NULL DEFAULT 'not_sent', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'paid', "paymentMode" "public"."invoices_paymentmode_enum" NOT NULL DEFAULT 'cash', "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "itemDiscountAmount" numeric(12,2) NOT NULL DEFAULT '0', "couponDiscountAmount" numeric(12,2) NOT NULL DEFAULT '0', "manualDiscountAmount" numeric(12,2) NOT NULL DEFAULT '0', "taxAmount" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL DEFAULT '0', "couponCode" character varying(60), "notes" character varying(800), "customerSnapshot" jsonb, "totalsSnapshot" jsonb, "linesSnapshot" jsonb, "syncedFromPos" boolean NOT NULL DEFAULT false, "sourceCreatedAt" TIMESTAMP WITH TIME ZONE, "cancelledAt" TIMESTAMP WITH TIME ZONE, "cancelledReason" character varying(400), "refundedAt" TIMESTAMP WITH TIME ZONE, "refundedReason" character varying(400), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invoices_idempotency_key_unique" ON "invoices" ("idempotencyKey") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invoices_invoice_number_unique" ON "invoices" ("invoiceNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_lines_linetype_enum" AS ENUM('item', 'add_on', 'combo', 'product', 'custom')`);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "lineType" "public"."invoice_lines_linetype_enum" NOT NULL, "referenceId" uuid, "nameSnapshot" character varying(180) NOT NULL, "quantity" numeric(14,3) NOT NULL DEFAULT '0', "unitPrice" numeric(12,2) NOT NULL DEFAULT '0', "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "gstPercentage" numeric(6,2) NOT NULL DEFAULT '0', "lineTotal" numeric(12,2) NOT NULL DEFAULT '0', "meta" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_lines_invoice_id" ON "invoice_lines" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payments_mode_enum" AS ENUM('cash', 'card', 'upi', 'mixed')`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payments_status_enum" AS ENUM('success', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "invoice_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "mode" "public"."invoice_payments_mode_enum" NOT NULL, "status" "public"."invoice_payments_status_enum" NOT NULL DEFAULT 'success', "amount" numeric(12,2) NOT NULL DEFAULT '0', "receivedAmount" numeric(12,2), "changeAmount" numeric(12,2), "referenceNo" character varying(120), "paidAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e19c9ebfa432289f510de7b4e99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_payments_invoice_id" ON "invoice_payments" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_activities_actiontype_enum" AS ENUM('created', 'synced', 'cancelled', 'refunded', 'updated')`);
        await queryRunner.query(`CREATE TABLE "invoice_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "actionType" "public"."invoice_activities_actiontype_enum" NOT NULL, "reason" character varying(400), "performedByUserId" uuid, "payload" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cff57f905c58df3725310df5f46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_activities_invoice_id" ON "invoice_activities" ("invoiceId") `);
        await queryRunner.query(`CREATE TABLE "invoice_usage_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "idempotencyKey" character varying(120), "invoiceId" uuid, "ingredientId" uuid, "ingredientNameSnapshot" character varying(180) NOT NULL, "consumedQuantity" numeric(14,6) NOT NULL DEFAULT '0', "baseUnit" character varying(24) NOT NULL, "allocatedQuantity" numeric(14,6) NOT NULL DEFAULT '0', "overusedQuantity" numeric(14,6) NOT NULL DEFAULT '0', "usageDate" date NOT NULL, "deviceId" character varying(80), "staffId" uuid, "meta" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7f39c969e6253e48a1b3de158b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_usage_events_invoice_id" ON "invoice_usage_events" ("invoiceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invoice_usage_events_idempotency_unique" ON "invoice_usage_events" ("idempotencyKey") `);
        await queryRunner.query(`CREATE TABLE "sync_receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "idempotencyKey" character varying(120) NOT NULL, "eventType" character varying(60) NOT NULL, "entityType" character varying(60), "entityId" character varying(120), "deviceId" character varying(80), "staffId" uuid, "status" character varying(24) NOT NULL DEFAULT 'processed', "requestPayload" jsonb, "responsePayload" jsonb, "errorMessage" text, "processedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_79fd723f8a33f146795b5d9af65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_sync_receipts_idempotency_unique" ON "sync_receipts" ("idempotencyKey") `);
        await queryRunner.query(`CREATE TABLE "gaming_bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingNumber" character varying(64) NOT NULL, "bookingType" character varying(20) NOT NULL, "resourceCode" character varying(40) NOT NULL, "resourceLabel" character varying(120) NOT NULL, "resourceCodes" jsonb NOT NULL DEFAULT '[]'::jsonb, "customerGroup" jsonb NOT NULL DEFAULT '[]'::jsonb, "primaryCustomerName" character varying(120), "primaryCustomerPhone" character varying(20), "checkInAt" TIMESTAMP WITH TIME ZONE NOT NULL, "checkOutAt" TIMESTAMP WITH TIME ZONE, "hourlyRate" numeric(12,2) NOT NULL DEFAULT '0', "finalAmount" numeric(12,2) NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'ongoing', "paymentStatus" character varying(20) NOT NULL DEFAULT 'pending', "paymentMode" character varying(20), "foodOrderReference" character varying(80), "foodInvoiceNumber" character varying(64), "foodInvoiceStatus" character varying(20) NOT NULL DEFAULT 'none', "foodAndBeverageAmount" numeric(12,2) NOT NULL DEFAULT '0', "bookingChannel" character varying(40), "sourceDeviceId" character varying(80), "note" text, "staffId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_25792920c36831a9a678220fefc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_gaming_bookings_check_in" ON "gaming_bookings" ("checkInAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_gaming_bookings_resource" ON "gaming_bookings" ("resourceCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_gaming_bookings_status" ON "gaming_bookings" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_gaming_bookings_booking_number_unique" ON "gaming_bookings" ("bookingNumber") `);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseNumber" character varying(64) NOT NULL, "supplierId" uuid NOT NULL, "purchaseDate" date NOT NULL, "purchaseType" character varying(20) NOT NULL, "totalAmount" numeric(12,2) NOT NULL DEFAULT '0', "note" text, "invoiceImageUrl" text, "createdByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_orders_date" ON "purchase_orders" ("purchaseDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_purchase_orders_number_unique" ON "purchase_orders" ("purchaseNumber") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseOrderId" uuid NOT NULL, "lineType" character varying(20) NOT NULL, "ingredientId" uuid, "productId" uuid, "itemNameSnapshot" character varying(180) NOT NULL, "categoryNameSnapshot" character varying(140), "unit" character varying(30) NOT NULL, "stockBefore" numeric(12,3) NOT NULL DEFAULT '0', "stockAdded" numeric(12,3) NOT NULL, "enteredQuantity" numeric(12,3), "enteredUnit" character varying(30), "stockAfter" numeric(12,3) NOT NULL DEFAULT '0', "unitPrice" numeric(12,2) NOT NULL, "lineTotal" numeric(12,2) NOT NULL, "unitPriceUpdated" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_34a2082d2abb10c5d8713bc19b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_order_lines_type" ON "purchase_order_lines" ("lineType") `);
        await queryRunner.query(`CREATE INDEX "IDX_purchase_order_lines_order" ON "purchase_order_lines" ("purchaseOrderId") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "category" character varying(80) NOT NULL DEFAULT 'General', "sku" character varying(40), "packSize" character varying(60), "unit" character varying(24) NOT NULL, "currentStock" numeric(12,3) NOT NULL DEFAULT '0', "minStock" numeric(12,3) NOT NULL DEFAULT '0', "purchaseUnitPrice" numeric(12,2) NOT NULL DEFAULT '0', "defaultSupplierId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_products_category" ON "products" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_is_active" ON "products" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_products_name_unique" ON "products" ("name") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(140) NOT NULL, "storeName" character varying(160), "phone" character varying(20) NOT NULL, "address" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_suppliers_name_unique" ON "suppliers" ("name") `);
        await queryRunner.query(`CREATE TABLE "cash_audits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auditDate" date NOT NULL, "denominationCounts" jsonb NOT NULL DEFAULT '{}'::jsonb, "countedAmount" numeric(12,2) NOT NULL DEFAULT '0', "staffCashTakenAmount" numeric(12,2) NOT NULL DEFAULT '0', "enteredCardAmount" numeric(12,2) NOT NULL DEFAULT '0', "enteredUpiAmount" numeric(12,2) NOT NULL DEFAULT '0', "expectedCashAmount" numeric(12,2) NOT NULL DEFAULT '0', "expectedCardAmount" numeric(12,2) NOT NULL DEFAULT '0', "expectedUpiAmount" numeric(12,2) NOT NULL DEFAULT '0', "note" character varying(500), "createdByUserId" uuid NOT NULL, "approvedByAdminId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_de56bb2438f189a5927ce4f8a46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."dump_entries_entrytype_enum" AS ENUM('ingredient', 'item', 'product')`);
        await queryRunner.query(`CREATE TABLE "dump_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entryDate" date NOT NULL, "entryType" "public"."dump_entries_entrytype_enum" NOT NULL, "ingredientId" uuid, "itemId" uuid, "productId" uuid, "sourceName" character varying(180) NOT NULL, "quantity" numeric(14,3) NOT NULL, "unit" character varying(24) NOT NULL, "baseQuantity" numeric(14,3) NOT NULL DEFAULT '0', "baseUnit" character varying(24), "lossAmount" numeric(14,2) NOT NULL DEFAULT '0', "ingredientImpacts" jsonb NOT NULL DEFAULT '[]'::jsonb, "note" character varying(500), "createdByUserId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9cf3c810181e40a11a54806a967" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "outlets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "outletCode" character varying(16) NOT NULL, "outletName" character varying(160) NOT NULL, "location" character varying(240) NOT NULL, "managerName" character varying(140) NOT NULL, "managerPhone" character varying(20) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_01e50956df1c68625d0ddede996" UNIQUE ("outletCode"), CONSTRAINT "PK_4f218ad1778c5c01d7bf77bab02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "outlet_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transferNumber" character varying(32) NOT NULL, "transferDate" date NOT NULL, "fromOutletId" uuid NOT NULL, "fromOutletName" character varying(180) NOT NULL, "toOutletId" uuid NOT NULL, "toOutletName" character varying(180) NOT NULL, "lines" jsonb NOT NULL DEFAULT '[]'::jsonb, "lineCount" integer NOT NULL DEFAULT '0', "totalQuantity" numeric(14,3) NOT NULL DEFAULT '0', "totalValue" numeric(14,2) NOT NULL DEFAULT '0', "note" character varying(500), "createdByUserId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ea202be15f5337e323529950eeb" UNIQUE ("transferNumber"), CONSTRAINT "PK_7dc04e0ce9ae353c967430d078e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "outlet_ingredient_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "outletId" uuid NOT NULL, "ingredientId" uuid NOT NULL, "totalStock" numeric(14,3) NOT NULL DEFAULT '0', "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_88f2d74607d688ddf79be8e1d73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_outlet_ingredient_stock_unique" ON "outlet_ingredient_stocks" ("outletId", "ingredientId") `);
        await queryRunner.query(`CREATE TABLE "outlet_product_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "outletId" uuid NOT NULL, "productId" uuid NOT NULL, "totalStock" numeric(14,3) NOT NULL DEFAULT '0', "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4e5d119ea2c951ee3e8d62cdeb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_outlet_product_stock_unique" ON "outlet_product_stocks" ("outletId", "productId") `);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_3e24aad29f272e2606de0462420" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_8f7060de1f9dc5d70ed029a1747" FOREIGN KEY ("categoryId") REFERENCES "ingredient_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_stocks" ADD CONSTRAINT "FK_7ab41ce837971278c768894802b" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_stock_logs" ADD CONSTRAINT "FK_ad68003d69b8ec9f627f46c1011" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_allocations" ADD CONSTRAINT "FK_964c680b10794f87f911b9be78c" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_billing_controls" ADD CONSTRAINT "FK_56632b94dab6ab0050806ea6c93" FOREIGN KEY ("updatedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_closing_reports" ADD CONSTRAINT "FK_1f68996424a044c271d86b0658d" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_788929ed61ab78bb914f0d1931b" FOREIGN KEY ("categoryId") REFERENCES "item_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_ingredients" ADD CONSTRAINT "FK_b51de4cde52ce60b44e565599f0" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_ingredients" ADD CONSTRAINT "FK_89047dfaa0a16d3f8ef0730f066" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "add_on_ingredients" ADD CONSTRAINT "FK_d84be0504ada733e13df841e415" FOREIGN KEY ("addOnId") REFERENCES "add_ons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "add_on_ingredients" ADD CONSTRAINT "FK_e26d2dac8f2b6b482b61a0ba456" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "combo_items" ADD CONSTRAINT "FK_3b4ce71c9b99bd8b26ce0618408" FOREIGN KEY ("comboId") REFERENCES "combos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "combo_items" ADD CONSTRAINT "FK_b1edc6a5ad4aee65861a62d2734" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_8c912b0f614b4ecc2eb972478b4" FOREIGN KEY ("freeItemCategoryId") REFERENCES "item_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_f8f408e8dd53469d52d49dcaf4d" FOREIGN KEY ("freeItemId") REFERENCES "items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_a7b422cc0dbf863671255eaad57" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_f526503f2419217d16794648f29" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_9bc262451bc39c7fdef2af5dd39" FOREIGN KEY ("freeItemId") REFERENCES "items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_925b24d7fc2f9324ce972aee025" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_7a255aae875dc621bd2008d003b" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_c45df314ecc55ebdbe803a2ed78" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_9f57f31e620fe759b452feb776e" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" ADD CONSTRAINT "FK_3b2a25d4269ebe9d7ca0c1001d4" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_activities" ADD CONSTRAINT "FK_53d0b59c5eb08f6207b0e934c68" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_activities" ADD CONSTRAINT "FK_89ae36a5ae04074b0f47a084c77" FOREIGN KEY ("performedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" ADD CONSTRAINT "FK_ec22276a93261f70c8aae8119fb" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" ADD CONSTRAINT "FK_14f312413649524511771527958" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" ADD CONSTRAINT "FK_c5358b53b1d76c4e9ba31822e74" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gaming_bookings" ADD CONSTRAINT "FK_ac135d0e75af4bfca75da84f57e" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_0c3ff892a9f2ed16f59d31cccae" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_5e0069b01003c73a904f0e4d97b" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_64a3df78c26adc62cbcf15aa4a4" FOREIGN KEY ("purchaseOrderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_069d72d7e35e7308377dde7582b" FOREIGN KEY ("ingredientId") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_d96db03df749514dd9b5f36ad2b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_da5ae3aec351eabc7f9986e7df3" FOREIGN KEY ("defaultSupplierId") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_audits" ADD CONSTRAINT "FK_4399d7f670a6c676ff57bd81076" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_audits" ADD CONSTRAINT "FK_dfc999c0f528b01335a5f7ff0c8" FOREIGN KEY ("approvedByAdminId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dump_entries" ADD CONSTRAINT "FK_b1373aeed1cbe192a84be0068c5" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "outlet_transfers" ADD CONSTRAINT "FK_8b7fdab336e1bbd868ff3ba2002" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "outlet_transfers" DROP CONSTRAINT "FK_8b7fdab336e1bbd868ff3ba2002"`);
        await queryRunner.query(`ALTER TABLE "dump_entries" DROP CONSTRAINT "FK_b1373aeed1cbe192a84be0068c5"`);
        await queryRunner.query(`ALTER TABLE "cash_audits" DROP CONSTRAINT "FK_dfc999c0f528b01335a5f7ff0c8"`);
        await queryRunner.query(`ALTER TABLE "cash_audits" DROP CONSTRAINT "FK_4399d7f670a6c676ff57bd81076"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_da5ae3aec351eabc7f9986e7df3"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_d96db03df749514dd9b5f36ad2b"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_069d72d7e35e7308377dde7582b"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_64a3df78c26adc62cbcf15aa4a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_5e0069b01003c73a904f0e4d97b"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_0c3ff892a9f2ed16f59d31cccae"`);
        await queryRunner.query(`ALTER TABLE "gaming_bookings" DROP CONSTRAINT "FK_ac135d0e75af4bfca75da84f57e"`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" DROP CONSTRAINT "FK_c5358b53b1d76c4e9ba31822e74"`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" DROP CONSTRAINT "FK_14f312413649524511771527958"`);
        await queryRunner.query(`ALTER TABLE "invoice_usage_events" DROP CONSTRAINT "FK_ec22276a93261f70c8aae8119fb"`);
        await queryRunner.query(`ALTER TABLE "invoice_activities" DROP CONSTRAINT "FK_89ae36a5ae04074b0f47a084c77"`);
        await queryRunner.query(`ALTER TABLE "invoice_activities" DROP CONSTRAINT "FK_53d0b59c5eb08f6207b0e934c68"`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" DROP CONSTRAINT "FK_3b2a25d4269ebe9d7ca0c1001d4"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_9f57f31e620fe759b452feb776e"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_c45df314ecc55ebdbe803a2ed78"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_7a255aae875dc621bd2008d003b"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_925b24d7fc2f9324ce972aee025"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_9bc262451bc39c7fdef2af5dd39"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_f526503f2419217d16794648f29"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_a7b422cc0dbf863671255eaad57"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_f8f408e8dd53469d52d49dcaf4d"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_8c912b0f614b4ecc2eb972478b4"`);
        await queryRunner.query(`ALTER TABLE "combo_items" DROP CONSTRAINT "FK_b1edc6a5ad4aee65861a62d2734"`);
        await queryRunner.query(`ALTER TABLE "combo_items" DROP CONSTRAINT "FK_3b4ce71c9b99bd8b26ce0618408"`);
        await queryRunner.query(`ALTER TABLE "add_on_ingredients" DROP CONSTRAINT "FK_e26d2dac8f2b6b482b61a0ba456"`);
        await queryRunner.query(`ALTER TABLE "add_on_ingredients" DROP CONSTRAINT "FK_d84be0504ada733e13df841e415"`);
        await queryRunner.query(`ALTER TABLE "item_ingredients" DROP CONSTRAINT "FK_89047dfaa0a16d3f8ef0730f066"`);
        await queryRunner.query(`ALTER TABLE "item_ingredients" DROP CONSTRAINT "FK_b51de4cde52ce60b44e565599f0"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_788929ed61ab78bb914f0d1931b"`);
        await queryRunner.query(`ALTER TABLE "staff_closing_reports" DROP CONSTRAINT "FK_1f68996424a044c271d86b0658d"`);
        await queryRunner.query(`ALTER TABLE "pos_billing_controls" DROP CONSTRAINT "FK_56632b94dab6ab0050806ea6c93"`);
        await queryRunner.query(`ALTER TABLE "daily_allocations" DROP CONSTRAINT "FK_964c680b10794f87f911b9be78c"`);
        await queryRunner.query(`ALTER TABLE "ingredient_stock_logs" DROP CONSTRAINT "FK_ad68003d69b8ec9f627f46c1011"`);
        await queryRunner.query(`ALTER TABLE "ingredient_stocks" DROP CONSTRAINT "FK_7ab41ce837971278c768894802b"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_8f7060de1f9dc5d70ed029a1747"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_3e24aad29f272e2606de0462420"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_outlet_product_stock_unique"`);
        await queryRunner.query(`DROP TABLE "outlet_product_stocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_outlet_ingredient_stock_unique"`);
        await queryRunner.query(`DROP TABLE "outlet_ingredient_stocks"`);
        await queryRunner.query(`DROP TABLE "outlet_transfers"`);
        await queryRunner.query(`DROP TABLE "outlets"`);
        await queryRunner.query(`DROP TABLE "dump_entries"`);
        await queryRunner.query(`DROP TYPE "public"."dump_entries_entrytype_enum"`);
        await queryRunner.query(`DROP TABLE "cash_audits"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_suppliers_name_unique"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_name_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_category"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_purchase_order_lines_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_purchase_order_lines_type"`);
        await queryRunner.query(`DROP TABLE "purchase_order_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_purchase_orders_number_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_purchase_orders_date"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gaming_bookings_booking_number_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gaming_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gaming_bookings_resource"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gaming_bookings_check_in"`);
        await queryRunner.query(`DROP TABLE "gaming_bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sync_receipts_idempotency_unique"`);
        await queryRunner.query(`DROP TABLE "sync_receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_usage_events_idempotency_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_usage_events_invoice_id"`);
        await queryRunner.query(`DROP TABLE "invoice_usage_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_activities_invoice_id"`);
        await queryRunner.query(`DROP TABLE "invoice_activities"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_activities_actiontype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_payments_invoice_id"`);
        await queryRunner.query(`DROP TABLE "invoice_payments"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payments_mode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_lines_invoice_id"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_lines_linetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_invoice_number_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_idempotency_key_unique"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_paymentmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_kitchenstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_ordertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customers_phone_unique"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_expires_at"`);
        await queryRunner.query(`DROP TABLE "auth_sessions"`);
        await queryRunner.query(`DROP TABLE "coupon_usages"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discounttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_combo_item_unique"`);
        await queryRunner.query(`DROP TABLE "combo_items"`);
        await queryRunner.query(`DROP TABLE "combos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_add_on_ingredient_unique"`);
        await queryRunner.query(`DROP TABLE "add_on_ingredients"`);
        await queryRunner.query(`DROP TYPE "public"."add_on_ingredients_unit_enum"`);
        await queryRunner.query(`DROP TABLE "add_ons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_item_ingredient_unique"`);
        await queryRunner.query(`DROP TABLE "item_ingredients"`);
        await queryRunner.query(`DROP TYPE "public"."item_ingredients_unit_enum"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TABLE "item_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_staff_closing_reports_staff_reportDate_unique"`);
        await queryRunner.query(`DROP TABLE "staff_closing_reports"`);
        await queryRunner.query(`DROP TABLE "pos_billing_controls"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daily_allocation_ingredient_date_unique"`);
        await queryRunner.query(`DROP TABLE "daily_allocations"`);
        await queryRunner.query(`DROP TABLE "ingredient_stock_logs"`);
        await queryRunner.query(`DROP TYPE "public"."ingredient_stock_logs_type_enum"`);
        await queryRunner.query(`DROP TABLE "ingredient_stocks"`);
        await queryRunner.query(`DROP TABLE "ingredients"`);
        await queryRunner.query(`DROP TYPE "public"."ingredients_unit_enum"`);
        await queryRunner.query(`DROP TABLE "ingredient_categories"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
